development:
  host: redis://<%= ENV['HOST_DB'] || '0.0.0.0' %>
  port: <%= ENV['PORT_BROKER_DB'] || '6378'%>
  db: 0

test:
  host: redis://<%= ENV['HOST_DB'] || '0.0.0.0' %>
  port: <%= ENV['PORT_BROKER_DB'] || '6378'%>
  db: 0

production:
  host: redis://<%= ENV['HOST_DB'] || '0.0.0.0' %>
  port: <%= ENV['PORT_BROKER_DB'] || '6378'%>
  db: 0

