development:
  #host: "redis://172.24.25.69"
  host: "redis://0.0.0.0"
  port: 6379
  db: 0

test:
  host: "redis://172.24.25.69"
  port: 6379
  db: 0

production:
  host: "redis://172.24.25.69"
  port: 6379
  db: 0
